### ISSUE TITLE
axobject-query doest not provide an export named 'AXObjectRoles' 

### ISSUE THREAD

**Issue by oyham** [A11yance/axobject-query#353]
This error occurs to me when performing Run Dev with NPM or PNPM. I've already tried to try astro 3.0.0, I've tried trying different cmds. Reinstalling the node_modules folder and performing fixes. 

![astroerr](https://github.com/A11yance/axobject-query/assets/97111287/b269d6b5-1f85-4a1f-ab8f-7138a1d42059)
![astroweb](https://github.com/A11yance/axobject-query/assets/97111287/846a4f2b-6688-42ae-8f3d-34a1959e7581)

**Comment by graybushlabs** [comment]
Having the same issue. I created the project from the template as instructed in the docs. I added tailwind but no other dependencies.

```
SyntaxError: The requested module '/@fs/F:/Code/graybushlabs/website/node_modules/axobject-query/lib/index.js?v=c1b914e4' does not provide an export named 'AXObjectRoles' (at a11y.js?v=c1b914e4:26:10)
```

**Comment by JaydenWN** [comment]
I'm experiencing this now. Any fix? Think it could be a vite issue.

**Comment by JaydenWN** [comment]
> I'm experiencing this now. Any fix? Think it could be a vite issue.

Disabling my VS code extensions fixed the issue. It could have been a Salesforce one or something, not sure.

Try running in terminal:
code --disable-extensions

then npm run dev.

**Comment by ljharb** [comment]
The package definitely provides that export, and the `/@fs/@D` in the OP suggests some kind of filesystem shenanigans, so it seems pretty clear it's due to whatever's setting up that mapping (astro perhaps?), and not due to this package.
