### ISSUE TITLE
Every file is executable

### ISSUE THREAD

**Issue by aaronjensen** [A11yance/axobject-query#9]
I was looking into something and noticed that this commit: https://github.com/A11yance/axobject-query/commit/c157720b5a6961a6d4ab7c3f846e64f4db780fac made every file in the repo executable (`chmod +x`). I'm guessing this wasn't intentional so I wanted to point it out.

Cheers!

**Comment by jessebeach** [comment]
🤦 

Thank you @aaronjensen for pointing this out. I'll fix it. Oy oy oy.
